version: "3.8"

services:
  spotify-sorter:
    build: .
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - spotify-sorter:/app/config
    env_file:
      - path: .env
        required: true

volumes:
  spotify-sorter: